# print("samrat")
# print("*" * 5)
# myName = input("Whats your name? ")
# color = input("Whats your favorite color? ")
# print(myName + " likes " + color)
birthYear = input("Whats your birth year? ")
print(type(birthYear))
birthYear = int(birthYear)
print(type(birthYear))
